[package]
name = "raygun"
version = "0.1.0"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]

[dependencies]
argparse = "0.2.1"
image = "0.15.0"
nom = "3.2.0"
liquid = "0.10.0"
log = "0.3.8"
simplelog = "0.4.2"

[dev-dependencies]
hamcrest = "0.1.3"

[profile.test]
opt-level = 0
debug = true