[package]
name = "raygun"
version = "0.1.0"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]

[dependencies]
argparse = "0.2.1"
downcast = "0.9.1"
float-cmp = "0.2.5"
image = "0.17.0"
liquid = "0.10.1"
log = "0.3.8"
rayon = "0.8.2"
simplelog = "0.4.2"

[dependencies.nom]
version = "3.2.0"
# features = ["verbose-errors"]

[profile.test]
opt-level = 0
debug = true
