[package]
name = "raygun"
version = "0.1.0"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]

[dependencies]
argparse = "0.2.1"
downcast = "0.9.0"
float-cmp = "0.2.4"
image = "0.15.0"
liquid = "0.10.0"
log = "0.3.8"
nom = "3.2.0"
simplelog = "0.4.2"

[profile.test]
opt-level = 0
debug = true