[package]
name = "raygun"
version = "0.1.0"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]

[dependencies]
image = "0.15.0"
nom = "3.2.0"
liquid = "0.10.0"

[profile.test]
opt-level = 0
debug = true