[package]
name = "raygun"
version = "0.1.0"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]

[dependencies]
#clap = "1.4.7"
image = "0.4.1"
combine = "1.2.0"
nom = "1.2.0"

[profile.test]
opt-level = 0
debug = true