[package]
name = "raygun"
version = "0.1.0"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2"
image = "0.23"
log = "0.4"
rayon = "1.3"
simplelog = "0.8"

raygun-material = { path="../../lib/raygun-material" }
raygun-math = { path="../../lib/raygun-math" }
raygun-primitives = { path="../../lib/raygun-primitives" }
raygun-scene = { path="../../lib/raygun-scene" }
raygun-scenefile = { path="../../lib/raygun-scenefile" }